[tool.ruff]
# Never enforce `E501`.
extend-select = [
  # isort
  "I",
  # pydocstyle
  "D",
  # pyupgrade
  "U",
  # pep8-naming
  "N",
  # flake8-bandit
  "S",
  # flake8-comprehensions
  "C",
  # flake8-bugbear
  "B",
  # flake8-builtins
  "A",
  # flake8-tidy-imports
  "I25",
  # flake8-print
  # "T",
  # flake8-quotes
  "Q",
  # flake8-annotations
  "ANN",
  # flake8-2020
  "YTT",
  # flake8-blind-except
  "BLE",
  # flake8-boolean-trap
  "FBT",
  # mccabe
  "C90",
  # Ruff-specific rules
  "RUF",
  # Meta rules
  "M",
]
ignore = ["E501"]
extend-ignore = ["ANN", "C90", "D"]
