ci:
    skip: [refurb, luacheck, format-xmllint, markdownlint, actionlint, sourcery]
default_language_version:
  python: python3.12
  ruby: 2.7.2

exclude: ^(cookiecutter)/
repos:
  # Standard hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-xml
      - id: check-yaml
        args: ['--allow-multiple-documents']
      - id: debug-statements
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: name-tests-test
      - id: pretty-format-json
        args: ['--autofix']
      - id: requirements-txt-fixer
      - id: sort-simple-yaml
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: refurb
        name: refurb
        language: system
        pass_filenames: false
        entry: pixi run refurb scripts/.local/bin
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.7
    hooks:
      - id: ruff
        args: ['--output-format=full', '--fix', '--config', 'ruff/.config/ruff/pyproject.toml']
      - id: ruff-format
  # Spelling
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: ['--write-changes',
               '--ignore-words=.pre-commit/codespell_words',
               '--exclude-file=.pre-commit/codespellignorelines',
               '--skip=.github/.cspell/*.txt']
  # - repo: https://github.com/streetsidesoftware/cspell-cli
  #   rev: v6.2.0
  #   hooks:
  #     - id: cspell
  # Lua
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.20.0
    hooks:
      - id: stylua-github
        args: ['--config-path', 'stylua/.config/stylua/.stylua.toml']
  - repo: https://github.com/Calinou/pre-commit-luacheck
    rev: v1.0.0
    hooks:
      - id: luacheck
  # Docker
  - repo: https://github.com/hadolint/hadolint
    rev: v2.13.0-beta
    hooks:
      - id: hadolint-docker
        args: ['--config', 'hadolint/.config/hadolint.yaml']
  # XML
  - repo: https://github.com/lsst-ts/pre-commit-xmllint
    rev: 6f36260b537bf9a42b6ea5262c915ae50786296e
    hooks:
      - id: format-xmllint
  # C++
  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v15.0.7
  #   hooks:
  #     - id: clang-format
  # Shell
  # - repo: https://github.com/koalaman/shellcheck-precommit
  #   rev: v0.9.0
  #   hooks:
  #   - id: shellcheck
  #     args: ['-x']
  # Markdown
  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
    - id: markdownlint
  - repo: https://github.com/s-weigand/pre-commit_mirrors-actionlint
    rev: v1.6.24
    hooks:
      - id: actionlint
  - repo: https://github.com/sourcery-ai/sourcery
    rev: v1.22.0
    hooks:
    - id: sourcery
      # The best way to use Sourcery in a pre-commit hook:
      # * review only changed lines:
      # * omit the summary
      args: [--diff=git diff HEAD, --enable=gpsg, --enable=default, --no-summary]
