name: myconfigs

channels:
  - conda-forge

dependencies:
  - python=3.12.0
  - requests
  - cookiecutter
  - argcomplete
  - refurb
  - pre-commit
  - debugpy
  - pip
  - pip:
    - jinja2_stringcase
