[tool.ruff]
# Never enforce `E501`.
extend-select = [
  # Enabled by default
  # pyflakes
  # "F",
  # pycodestyle
  # "E",
  "W",
  # mccabe
  "C90",
  # isort
  "I",
  # pydocstyle
  "D",
  # pyupgrade
  "UP",
  # pep8-naming
  "N",
  # flake8-2020
  "YTT",
  # flake8-annotations
  "ANN",
  # flake8-bandit
  "S",
  # flake8-blind-except
  "BLE",
  # flake8-boolean-trap
  "FBT",
  # flake8-bugbear
  "B",
  # flake8-builtins
  "A",
  # flake8-comprehensions
  "C4",
  # flake-debugger
  "T10",
  # flake8-errmsg
  "EM",
  # lake8-import-conventions
  "ICN",
  # flake8-print
  # "T20",
  # flake8-quotes
  "Q",
  # flake8-return
  "RET",
  # flake8-simplify
  "SIM",
  # flake8-tidy-imports
  "TID",
  # flake8-unused-arguments
  # "ARG",
  # flake8-datetimez
  "DTZ",
  # eradicate
  "ERA",
  # pandas-vet
  "PD",
  # pygrep-hooks
  "PGH",
  # Pylint
  "PLC",
  "PLE",
  "PLR",
  "PLW",
  # Ruff-specific rules
  "RUF",
]
ignore = ["E501"]
extend-ignore = ["ANN", "C90", "D"]
exclude = ["cookiecutter"]
