[General]
checkForUpdates=true
# i3/x11 has xdg-desktop-portal, but its gtk backend has no Screenshot interface.
# Flameshot v14 needs this to bypass the portal and capture via native X11.
useX11LegacyScreenshot=true
contrastOpacity=188
showStartupLaunchMessage=false
startupLaunch=false
