Index:
  StandardLibrary: Yes
Hover:
  ShowAKA: Yes
CompileFlags:
  # https://github.com/cpp-best-practices/cppbestpractices/blob/master/02-Use_the_Tools_Available.md#compilers
  Add: [-Wall,
        -Wextra,
        -Wlifetime,
        -Wformat=2,
        -Wold-style-cast,
        -Woverloaded-virtual,
        -Wduplicated-cond,
        -Wduplicated-branches,
        -Wlogical-op,
        -Wnull-dereference,
        -Wshadow,
        -Wnon-virtual-dtor,
        -Wimplicit-fallthrough,
        -pedantic]
Diagnostics:
  # https://clang.llvm.org/extra/clang-tidy/checks/list.html
  ClangTidy:
    Add: [modernize*,
          cppcoreguidelines*,
          bugprone*,
          boost*,
          clang-analyzer*,
          concurrency*,
          readability*,
          performance*,
          google*,
          misc*]
    Remove: [modernize-use-trailing-return-type,
             cppcoreguidelines-avoid-magic-numbers,
             readability-magic-numbers,
             readability-identifier-length,
             readability-braces-around-statements,
             google-readability-braces-around-statements,
             google-readability-todo,
             cppcoreguidelines-owning-memory,
             readability-uppercase-literal-suffix,
             cppcoreguidelines-special-member-functions,
             cppcoreguidelines-avoid-non-const-global-variables]
  UnusedIncludes: Strict
InlayHints:
  Designators: No
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
