#!/usr/bin/python3
# -*- coding: utf-8 -*-

import argparse
import pathlib

import argcomplete
from utils import run_command


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--build-dir", default="build")
    parser.add_argument("--dry-run", action="store_true", help="")
    argcomplete.autocomplete(parser)
    args = parser.parse_args()

    package_build_path = pathlib.Path(args.build_dir).resolve()
    package_path = pathlib.Path(".").resolve()
    cmd = ["cmake", "..", "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"]
    run_command(cmd, args.dry_run, package_build_path)

    clang_tidy_cmd = [
        "run-clang-tidy",
        "-fix",
        f"-header-filter={package_path}/.*",
        f"-p={package_build_path}",
        ".",
    ]
    run_command(clang_tidy_cmd, args.dry_run, package_path)


if __name__ == "__main__":
    main()
