#!/usr/bin/python3

import argparse
import json
import os
import re

import argcomplete
from utils import (
    ROS_VERSIONS,
    PackagesCompleter,
    call,
    get_package_paths,
    get_ros_packages,
    get_ros_version,
    run_command,
)

PATTERN = re.compile(r"\d* tests collected in \d*.\d*s")


def get_tests(package_name):
    tests = []
    src_dir, build_dir = get_package_paths(package_name)
    parsed_output = json.loads(
        call(
            [
                "ctest",
                "--show-only=json-v1",
                "--test-dir",
                build_dir,
            ]
        )
    )
    for test in parsed_output["tests"]:
        tests.append(test["name"] + "@ctest")

    # TODO: Why this returns an empty string inside this function, it works when called outside
    # parsed_output = call(
    #     [
    #         "python3",
    #         "-m",
    #         "pytest",
    #         "--color=no",
    #         "--collect-only",
    #         "--quiet",
    #         "--",
    #         src_dir,
    #     ]
    # )

    # for line in parsed_output.split("\n"):
    #     if len(line) and not PATTERN.match(line):
    #         tests.append(line + "@pytest")

    return tests


class TestCompleter:
    def __call__(self, prefix, parsed_args, **kwargs):
        return get_tests(parsed_args.pkg[0])


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--pkg", nargs="+").completer = PackagesCompleter(
        get_ros_packages(os.path.abspath(os.curdir) + "/src")
    )
    # nargs??? for ctest it's -L??
    parser.add_argument("--test").completer = TestCompleter()
    parser.add_argument("--verbose", action="store_true", help="")
    parser.add_argument("--dry-run", action="store_true", help="")
    argcomplete.autocomplete(parser)
    args = parser.parse_args()

    cmd = []
    ROS_VERSION = get_ros_version()
    if ROS_VERSION == ROS_VERSIONS.UNKNOWN:
        print("Unknown ROS version")
        return
    if ROS_VERSION == ROS_VERSIONS.ROS1:
        cmd += ["catkin", "build"]
        if args.pkg:
            cmd += args.pkg
            cmd += ["--no-deps"]
        if args.verbose:
            cmd += ["--verbose"]
        cmd += ["--catkin-make-args", "run_tests"]
    elif ROS_VERSION == ROS_VERSIONS.ROS2:
        cmd += ["colcon", "test"]
        if args.pkg:
            cmd += ["--packages-select"]
            cmd += args.pkg
        if args.verbose:
            cmd += ["--event-handlers", "console_direct+"]
        if args.test:
            test, type = args.test.split("@")
            if type == "pytest":
                cmd += ["--pytest-args", test]
            elif type == "ctest":
                cmd += ["--ctest-args", "--tests-regex", test]
    run_command(cmd, args.dry_run)


if __name__ == "__main__":
    main()
