# https://containertoolbx.org/distros/
FROM docker.io/library/debian:sid

ENV NAME=debian-toolbox VERSION=sid

LABEL com.github.containers.toolbox="true" \
      com.github.debarshiray.toolbox="true" \
      name="$NAME" \
      version="$VERSION"

RUN apt update
RUN apt -y upgrade

RUN apt -y install software-properties-common
RUN apt-add-repository ppa:fish-shell/release-3

COPY extra-packages /
RUN apt -y install $(cat extra-packages | xargs)
RUN rm /extra-packages

RUN sed -i -e 's/ ALL$/ NOPASSWD:ALL/' /etc/sudoers

RUN apt clean

RUN echo VARIANT_ID=container >> /etc/os-release
RUN touch /etc/localtime

CMD /bin/fish
