--    use("github/copilot.vim")
--    -- LSP clients configurations
--    use("krady21/compiler-explorer.nvim")
--    -- Debugger
--    use({
--      "mfussenegger/nvim-dap",
--      requires = {
--        "rcarriga/nvim-dap-ui",
--        "theHamsta/nvim-dap-virtual-text",
--        "mfussenegger/nvim-dap-python",
--      },
--    })
