name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install luacheck
        run: sudo apt update && sudo apt-get install luarocks libxml2-utils && sudo luarocks install luacheck
      - uses: prefix-dev/setup-pixi@v0.8.0
        with:
          pixi-version: v0.22.0
          cache: true
      - run: |
          pixi run pip install sourcery
          pixi run sourcery login --token ${{ secrets.SOURCERY_TOKEN }}
      - run: pixi run lint
