name: Format

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install luacheck
        run: sudo apt-get install luarocks && sudo luarocks install luacheck
      - name: Install micromamba
        shell: bash -leo pipefail {0}
        run: |
          mkdir -p ~/.local/bin
          curl -Ls https://micro.mamba.pm/api/micromamba/linux-64/latest | tar -xvj -C ~/.local/bin/ --strip-components=1 bin/micromamba
          micromamba shell init -s bash -p ~/micromamba
          export MAMBA_ROOT_PREFIX=~/micromamba
          export MAMBA_EXE=~/.local/bin/micromamba
          . $MAMBA_ROOT_PREFIX/etc/profile.d/micromamba.sh
          # export MAMBA_ROOT_PREFIX=~/micromamba
          # eval "$(micromamba shell hook --shell bash --prefix ~/micromamba)"
          # # source ~/.bashrc
          micromamba create --name refurb --prefix ~/micromamba
          micromamba install refurb -c conda-forge
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.3
